version: "3.3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
      # - ./db:/app/
    restart: always
    env_file: .docker.env

  backend:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./backend_app:/app/
    command: sh /start.sh
    restart: on-failure
    env_file: .docker.env
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./front_end_app:/app
      - ./settings/nginx/dev.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none
