version: "2"
services:
  base:
    image: node:10-alpine
    volumes:
      - ./front_end_app:/app
    working_dir: /app

  install:
    extends:
      service: base
    command: npm i

  build:
    extends:
      service: base
    command: npm run build
