version: "3.3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
      # - ./db:/app/
    restart: always
    env_file: .docker.env

  backend:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./backend_app:/app/
    command: sh /start.sh
    restart: on-failure
    env_file: .docker.env
    expose:
      - "9000"

  nginx:
    # https://github.com/staticfloat/docker-nginx-certbot
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: owner@company.com
    volumes:
      - ./front_end_app:/app
      - ./settings/nginx/conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
